package vn.gpay.jitin.core.utils;

public class OrgType {
	public static int ORG_TYPE_TRUSOCHINH = 1;
	public static int ORG_TYPE_CHINHANH = 2;
	public static int ORG_TYPE_KHONGUYENLIEU = 3;
	public static int ORG_TYPE_CUAHANG = 4;
	public static int ORG_TYPE_NHACUNGCAP = 5;
	public static int ORG_TYPE_CHUHANGGIACONG = 6;
	public static int ORG_TYPE_DONVIGIACONG = 7;
	public static int ORG_TYPE_KHOTHANHPHAM = 8;
	public static int ORG_TYPE_HOANTHIEN = 9;
	public static int ORG_TYPE_KHACHHANG = 10;
	public static int ORG_TYPE_VENDOR = 11;
	public static int ORG_TYPE_ENDBUYER = 12;
	public static int ORG_TYPE_XUONGSX = 13;
	public static int ORG_TYPE_CHUYEN = 14;
	public static int ORG_TYPE_CANG = 15;
	public static int ORG_TYPE_DONVIQC = 16;
	public static int ORG_TYPE_CAT = 17;
	public static int ORG_TYPE_KHOPHULIEU = 19;
	public static int ORG_TYPE_INTHEU = 20;
	public static int ORG_TYPE_TOGIATLA = 21;
	public static int ORG_TYPE_PHONGBAN = 22;
	public static int ORG_TYPE_DONVIGIATLA = 23;
	public static int ORG_TYPE_QUOCTICH = 24;
	public static int ORG_TYPE_THANHPHOTINH = 25;
	public static int ORG_TYPE_QUANHUYEN = 26;
	public static int ORG_TYPE_XA = 27;
	public static int ORG_TYPE_TOCODIEN 		= 28;
	public static int ORG_TYPE_KHONPL 			= 29;
	public static int ORG_TYPE_TOKYTHUAT 		= 30;
	public static int ORG_TYPE_TOVESINH 		= 31;
	public static int ORG_TYPE_VANPHONGXUONG 	= 32;
	public static int ORG_TYPE_TOCODONG 		= 33;
	public static int ORG_TYPE_FOB 				= 34;
	public static int ORG_TYPE_DONVIQA 			= 35;
	public static int ORG_TYPE_TOBAOVE 			= 36;
	public static int ORG_TYPE_KCS 				= 37;
	public static int ORG_TYPE_LAIXE 			= 38;
	public static int ORG_TYPE_BANCAT = 39;
}
